plugins:
  - name: solidity

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.4.0

solidity: 
  import_remapping:
    - "@openzeppelin=OpenZeppelin/4.4.0"

deployments:
  ethereum:
    rinkeby: 
    - contract_type: PoofPoof
      address: 0xc326C44728208F55e11AC24536b6AB207A4a9E03
